// This file is "model.dart"
import 'package:dart_mappable/dart_mappable.dart';
import 'package:shadcn/src/constants.dart';
import 'package:version/version.dart';

// Will be generated by dart_mappable
part 'pubspec.mapper.dart';

@MappableClass()
class Pubspec with PubspecMappable {
  const Pubspec({
    this.name,
    this.version,
    this.description,
    this.dependencies,
    this.devDependencies,
    this.environment,
  });

  final String? name;
  final String? version;
  final String? description;
  final Map<String, dynamic>? dependencies;
  final Map<String, dynamic>? devDependencies;
  final Map<String, dynamic>? environment;

  ({bool success, String? errorMessage}) satifiesMinFlutterVersion() {
    final flutterVersion = environment?['flutter'];
    if (flutterVersion is String) {
      final versionString = flutterVersion.split('>=')[1].trim();
      final version = Version.parse(versionString);
      return (success: version >= kMinFlutterVersion, errorMessage: null);
    }
    return (
      success: false,
      errorMessage:
          'Flutter not found in the environment section of pubspec.yaml',
    );
  }
}
