// This file is "model.dart"
import 'package:dart_mappable/dart_mappable.dart';

// Will be generated by dart_mappable
part 'pubspec.mapper.dart';

@MappableClass()
class Pubspec with PubspecMappable {
  const Pubspec({
    this.name,
    this.version,
    this.description,
    this.dependencies,
    this.devDependencies,
    this.environment,
  });

  final String? name;
  final String? version;
  final String? description;
  final Map<String, dynamic>? dependencies;
  final Map<String, dynamic>? devDependencies;
  final Map<String, dynamic>? environment;
}
