include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    always_put_required_named_parameters_first: false
    prefer_asserts_with_message: false
    prefer_constructors_over_static_methods: false
    avoid_positional_boolean_parameters: false
    document_ignores: false
