import 'package:flutter/widgets.dart';
import 'package:shadcn_ui/src/theme/color_scheme/base.dart';

@immutable
class ShadOrangeColorScheme extends ShadColorScheme {
  const ShadOrangeColorScheme({
    required super.background,
    required super.foreground,
    required super.card,
    required super.cardForeground,
    required super.popover,
    required super.popoverForeground,
    required super.primary,
    required super.primaryForeground,
    required super.secondary,
    required super.secondaryForeground,
    required super.muted,
    required super.mutedForeground,
    required super.accent,
    required super.accentForeground,
    required super.destructive,
    required super.destructiveForeground,
    required super.border,
    required super.input,
    required super.ring,
    required super.selection,
    required super.sidebar,
    required super.sidebarForeground,
    required super.sidebarBorder,
    required super.sidebarRing,
    required super.sidebarAccent,
    required super.sidebarAccentForeground,
    required super.sidebarPrimary,
    required super.sidebarPrimaryForeground,
    super.custom,
  });

  const ShadOrangeColorScheme.light({
    super.background = const Color(0xffffffff),
    super.foreground = const Color(0xff0c0a09),
    super.card = const Color(0xffffffff),
    super.cardForeground = const Color(0xff0c0a09),
    super.popover = const Color(0xffffffff),
    super.popoverForeground = const Color(0xff0c0a09),
    super.primary = const Color(0xfff97316),
    super.primaryForeground = const Color(0xfffafaf9),
    super.secondary = const Color(0xfff5f5f4),
    super.secondaryForeground = const Color(0xff1c1917),
    super.muted = const Color(0xfff5f5f4),
    super.mutedForeground = const Color(0xff78716c),
    super.accent = const Color(0xfff5f5f4),
    super.accentForeground = const Color(0xff1c1917),
    super.destructive = const Color(0xffef4444),
    super.destructiveForeground = const Color(0xfffafaf9),
    super.border = const Color(0xffe7e5e4),
    super.input = const Color(0xffe7e5e4),
    super.ring = const Color(0xfff97316),
    super.selection = const Color(0xFFB4D7FF),
    super.sidebar = const Color(0xFFfafafa),
    super.sidebarForeground = const Color(0xFF09090b),
    super.sidebarAccent = const Color(0xFFf4f4f5),
    super.sidebarAccentForeground = const Color(0xFF18181b),
    super.sidebarBorder = const Color(0xFFe4e4e7),
    super.sidebarPrimary = const Color(0xFFff6900),
    super.sidebarPrimaryForeground = const Color(0xFFfff7ed),
    super.sidebarRing = const Color(0xFFff6900),
    super.custom,
  });

  const ShadOrangeColorScheme.dark({
    super.background = const Color(0xff0c0a09),
    super.foreground = const Color(0xfffafaf9),
    super.card = const Color(0xff0c0a09),
    super.cardForeground = const Color(0xfffafaf9),
    super.popover = const Color(0xff0c0a09),
    super.popoverForeground = const Color(0xfffafaf9),
    super.primary = const Color(0xffea580c),
    super.primaryForeground = const Color(0xfffafaf9),
    super.secondary = const Color(0xff292524),
    super.secondaryForeground = const Color(0xfffafaf9),
    super.muted = const Color(0xff292524),
    super.mutedForeground = const Color(0xffa8a29e),
    super.accent = const Color(0xff292524),
    super.accentForeground = const Color(0xfffafaf9),
    super.destructive = const Color(0xffef4444),
    super.destructiveForeground = const Color(0xfffafaf9),
    super.border = const Color(0xff292524),
    super.input = const Color(0xff292524),
    super.ring = const Color(0xffea580c),
    super.selection = const Color(0xFF355172),
    super.sidebar = const Color(0xFF18181b),
    super.sidebarForeground = const Color(0xFFfafafa),
    super.sidebarAccent = const Color(0xFF27272a),
    super.sidebarAccentForeground = const Color(0xFFfafafa),
    super.sidebarBorder = const Color.fromRGBO(255, 255, 255, 0.102),
    super.sidebarPrimary = const Color(0xFFf54900),
    super.sidebarPrimaryForeground = const Color(0xFFfff7ed),
    super.sidebarRing = const Color(0xFFf54900),
    super.custom,
  });
}
