import 'package:flutter/widgets.dart';
import 'package:shadcn_ui/src/theme/color_scheme/base.dart';

@immutable
class ShadVioletColorScheme extends ShadColorScheme {
  const ShadVioletColorScheme({
    required super.background,
    required super.foreground,
    required super.card,
    required super.cardForeground,
    required super.popover,
    required super.popoverForeground,
    required super.primary,
    required super.primaryForeground,
    required super.secondary,
    required super.secondaryForeground,
    required super.muted,
    required super.mutedForeground,
    required super.accent,
    required super.accentForeground,
    required super.destructive,
    required super.destructiveForeground,
    required super.border,
    required super.input,
    required super.ring,
    required super.selection,
    required super.sidebar,
    required super.sidebarForeground,
    required super.sidebarBorder,
    required super.sidebarRing,
    required super.sidebarAccent,
    required super.sidebarAccentForeground,
    required super.sidebarPrimary,
    required super.sidebarPrimaryForeground,
    super.custom,
  });

  const ShadVioletColorScheme.light({
    super.background = const Color(0xffffffff),
    super.foreground = const Color(0xff030712),
    super.card = const Color(0xffffffff),
    super.cardForeground = const Color(0xff030712),
    super.popover = const Color(0xffffffff),
    super.popoverForeground = const Color(0xff030712),
    super.primary = const Color(0xff7c3aed),
    super.primaryForeground = const Color(0xfff9fafb),
    super.secondary = const Color(0xfff3f4f6),
    super.secondaryForeground = const Color(0xff111827),
    super.muted = const Color(0xfff3f4f6),
    super.mutedForeground = const Color(0xff6b7280),
    super.accent = const Color(0xfff3f4f6),
    super.accentForeground = const Color(0xff111827),
    super.destructive = const Color(0xffef4444),
    super.destructiveForeground = const Color(0xfff9fafb),
    super.border = const Color(0xffe5e7eb),
    super.input = const Color(0xffe5e7eb),
    super.ring = const Color(0xff7c3aed),
    super.selection = const Color(0xFFB4D7FF),
    super.sidebar = const Color(0xFFfafafa),
    super.sidebarForeground = const Color(0xFF09090b),
    super.sidebarAccent = const Color(0xFFf4f4f5),
    super.sidebarAccentForeground = const Color(0xFF18181b),
    super.sidebarBorder = const Color(0xFFe4e4e7),
    super.sidebarPrimary = const Color(0xFF8e51ff),
    super.sidebarPrimaryForeground = const Color(0xFFf5f3ff),
    super.sidebarRing = const Color(0xFF8e51ff),
    super.custom,
  });

  const ShadVioletColorScheme.dark({
    super.background = const Color(0xff030712),
    super.foreground = const Color(0xfff9fafb),
    super.card = const Color(0xff030712),
    super.cardForeground = const Color(0xfff9fafb),
    super.popover = const Color(0xff030712),
    super.popoverForeground = const Color(0xfff9fafb),
    super.primary = const Color(0xff6d28d9),
    super.primaryForeground = const Color(0xfff9fafb),
    super.secondary = const Color(0xff1f2937),
    super.secondaryForeground = const Color(0xfff9fafb),
    super.muted = const Color(0xff1f2937),
    super.mutedForeground = const Color(0xff9ca3af),
    super.accent = const Color(0xff1f2937),
    super.accentForeground = const Color(0xfff9fafb),
    super.destructive = const Color(0xffef4444),
    super.destructiveForeground = const Color(0xfff9fafb),
    super.border = const Color(0xff1f2937),
    super.input = const Color(0xff1f2937),
    super.ring = const Color(0xff6d28d9),
    super.selection = const Color(0xFF355172),
    super.sidebar = const Color(0xFF18181b),
    super.sidebarForeground = const Color(0xFFfafafa),
    super.sidebarAccent = const Color(0xFF27272a),
    super.sidebarAccentForeground = const Color(0xFFfafafa),
    super.sidebarBorder = const Color.fromRGBO(255, 255, 255, 0.1),
    super.sidebarPrimary = const Color(0xFF7f22fe),
    super.sidebarPrimaryForeground = const Color(0xFFf5f3ff),
    super.sidebarRing = const Color(0xFF7f22fe),
    super.custom,
  });
}
