import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';
import 'package:shadcn_ui/src/theme/components/badge.dart';
import 'package:shadcn_ui/src/theme/data.dart';
import 'package:shadcn_ui/src/theme/components/button.dart';

@immutable
class ShadcnZincTheme extends ShadcnThemeData {
  const ShadcnZincTheme({
    required super.background,
    required super.foreground,
    required super.card,
    required super.cardForeground,
    required super.popover,
    required super.popoverForeground,
    required super.primary,
    required super.primaryForeground,
    required super.secondary,
    required super.secondaryForeground,
    required super.muted,
    required super.mutedForeground,
    required super.accent,
    required super.accentForeground,
    required super.destructive,
    required super.destructiveForeground,
    required super.border,
    required super.input,
    required super.ring,
    required super.radius,
    required super.brightness,
    required super.primaryButtonTheme,
    required super.secondaryButtonTheme,
    required super.destructiveButtonTheme,
    required super.outlineButtonTheme,
    required super.ghostButtonTheme,
    required super.linkButtonTheme,
    required super.primaryBadgeTheme,
    required super.secondaryBadgeTheme,
    required super.destructiveBadgeTheme,
    required super.outlineBadgeTheme,
  });

  factory ShadcnZincTheme.light({
    Color background = const Color(0xFFFFFFFF),
    Color foreground = const Color(0xff09090b),
    Color card = const Color(0xffffffff),
    Color cardForeground = const Color(0xff09090b),
    Color popover = const Color(0xffffffff),
    Color popoverForeground = const Color(0xff09090b),
    Color primary = const Color(0xff18181b),
    Color primaryForeground = const Color(0xfffafafa),
    Color secondary = const Color(0xfff4f4f5),
    Color secondaryForeground = const Color(0xff18181b),
    Color muted = const Color(0xfff4f4f5),
    Color mutedForeground = const Color(0xff71717a),
    Color accent = const Color(0xfff4f4f5),
    Color accentForeground = const Color(0xff18181b),
    Color destructive = const Color(0xffdc2626),
    Color destructiveForeground = const Color(0xfffafafa),
    Color border = const Color(0xffe4e4e7),
    Color input = const Color(0xffe4e4e7),
    Color ring = const Color(0xffa1a1aa),
    BorderRadius radius = const BorderRadius.all(Radius.circular(8)),
    ShadcnButtonTheme? primaryButtonTheme,
    ShadcnButtonTheme? secondaryButtonTheme,
    ShadcnButtonTheme? destructiveButtonTheme,
    ShadcnButtonTheme? outlineButtonTheme,
    ShadcnButtonTheme? ghostButtonTheme,
    ShadcnButtonTheme? linkButtonTheme,
    ShadcnBadgeTheme? primaryBadgeTheme,
    ShadcnBadgeTheme? secondaryBadgeTheme,
    ShadcnBadgeTheme? destructiveBadgeTheme,
    ShadcnBadgeTheme? outlineBadgeTheme,
  }) {
    return ShadcnZincTheme(
      brightness: Brightness.light,
      background: background,
      foreground: foreground,
      card: card,
      cardForeground: cardForeground,
      popover: popover,
      popoverForeground: popoverForeground,
      primary: primary,
      primaryForeground: primaryForeground,
      secondary: secondary,
      secondaryForeground: secondaryForeground,
      muted: muted,
      mutedForeground: mutedForeground,
      accent: accent,
      accentForeground: accentForeground,
      destructive: destructive,
      destructiveForeground: destructiveForeground,
      border: border,
      input: input,
      ring: ring,
      radius: radius,
      primaryButtonTheme: primaryButtonTheme,
      secondaryButtonTheme: secondaryButtonTheme,
      destructiveButtonTheme: destructiveButtonTheme,
      outlineButtonTheme: outlineButtonTheme,
      ghostButtonTheme: ghostButtonTheme,
      linkButtonTheme: linkButtonTheme,
      primaryBadgeTheme: primaryBadgeTheme,
      secondaryBadgeTheme: secondaryBadgeTheme,
      destructiveBadgeTheme: destructiveBadgeTheme,
      outlineBadgeTheme: outlineBadgeTheme,
    );
  }

  factory ShadcnZincTheme.dark({
    Color background = const Color(0xff09090b),
    Color foreground = const Color(0xfffafafa),
    Color card = const Color(0xff09090b),
    Color cardForeground = const Color(0xfffafafa),
    Color popover = const Color(0xff09090b),
    Color popoverForeground = const Color(0xfffafafa),
    Color primary = const Color(0xfffafafa),
    Color primaryForeground = const Color(0xff18181b),
    Color secondary = const Color(0xff27272a),
    Color secondaryForeground = const Color(0xfffafafa),
    Color muted = const Color(0xff27272a),
    Color mutedForeground = const Color(0xffa1a1aa),
    Color accent = const Color(0xff27272a),
    Color accentForeground = const Color(0xfffafafa),
    Color destructive = const Color(0xff7f1d1d),
    Color destructiveForeground = const Color(0xfffafafa),
    Color border = const Color(0xff27272a),
    Color input = const Color(0xff27272a),
    Color ring = const Color(0xffd4d4d8),
    BorderRadius radius = const BorderRadius.all(Radius.circular(8)),
    ShadcnButtonTheme? primaryButtonTheme,
    ShadcnButtonTheme? secondaryButtonTheme,
    ShadcnButtonTheme? destructiveButtonTheme,
    ShadcnButtonTheme? outlineButtonTheme,
    ShadcnButtonTheme? ghostButtonTheme,
    ShadcnButtonTheme? linkButtonTheme,
    ShadcnBadgeTheme? primaryBadgeTheme,
    ShadcnBadgeTheme? secondaryBadgeTheme,
    ShadcnBadgeTheme? destructiveBadgeTheme,
    ShadcnBadgeTheme? outlineBadgeTheme,
  }) {
    return ShadcnZincTheme(
      brightness: Brightness.dark,
      background: background,
      foreground: foreground,
      card: card,
      cardForeground: cardForeground,
      popover: popover,
      popoverForeground: popoverForeground,
      primary: primary,
      primaryForeground: primaryForeground,
      secondary: secondary,
      secondaryForeground: secondaryForeground,
      muted: muted,
      mutedForeground: mutedForeground,
      accent: accent,
      accentForeground: accentForeground,
      destructive: destructive,
      destructiveForeground: destructiveForeground,
      border: border,
      input: input,
      ring: ring,
      radius: radius,
      primaryButtonTheme: primaryButtonTheme,
      secondaryButtonTheme: secondaryButtonTheme,
      destructiveButtonTheme: destructiveButtonTheme,
      outlineButtonTheme: outlineButtonTheme,
      ghostButtonTheme: ghostButtonTheme,
      linkButtonTheme: linkButtonTheme,
      primaryBadgeTheme: primaryBadgeTheme,
      secondaryBadgeTheme: secondaryBadgeTheme,
      destructiveBadgeTheme: destructiveBadgeTheme,
      outlineBadgeTheme: outlineBadgeTheme,
    );
  }
}
