name: Flutter test

on:
  workflow_run:
    workflows: ["Build Runner Auto-commit"]
    types:
      - completed

jobs:
  check-imports:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/check-imports.yaml

  build:
    name: Flutter test
    runs-on: ubuntu-latest
    needs: check-imports
    concurrency:
      group: ${{ github.head_ref || github.run_id }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2.21.0
        with:
          channel: "stable"
          cache: true

      - name: Clean
        run: flutter clean

      - name: Install and analyze
        run: |
          flutter pub get
          cd cli && dart pub get
          cd ../playground && flutter pub get
          cd ..
          flutter analyze

      - name: Test
        run: flutter test -r github

      - name: Downgrade dependencies
        run: |
          flutter pub downgrade
          flutter analyze --no-fatal-infos --no-fatal-warnings
