name: Flutter test

on:
  pull_request_target:
    paths-ignore:
      - "**.md"
  push:
    branches:
      - main
      - dev
    paths-ignore:
      - "**.md"

jobs:
  build:
    name: Flutter test
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.head_ref || github.run_id }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2.18.0
        with:
          channel: "stable"
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Test
        run: flutter test
