name: Update Dart File Hashes

on:
  push:
    branches:
      - main

jobs:
  update-hashes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run hash generation script
        run: bash .github/scripts/generate_hashes.sh

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add cli/hashes.json
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update hashes.json with latest Dart file SHAs"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
